### ISSUE TITLE
No Potion Shift

### ISSUE THREAD

**Issue by alven-shin** [shedaniel/slight-gui-modifications#23]
It would be cool to re-center the inventory when you have potion effects because I find it annoying that having a potion effect shifts the entire inventory to the right even there is plenty of wasted space on the left.

**Comment by shedaniel** [comment]
Install [No Potion Offset](https://www.curseforge.com/minecraft/mc-mods/no-potion-offset), other of my mods.

**Comment by alven-shin** [comment]
Ah nice thank you, it works great. I did not notice the mod since it is not registered as a fabric mod and I was using gdlauncher.
