### ISSUE TITLE
Crashing: The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'slight-gui-modifications'! Exit Code: -1

### ISSUE THREAD

**Issue by Blueil** [shedaniel/slight-gui-modifications#30]
https://pastebin.com/U7hkuF6W
I reopened it after @shedaniel said to install auto config, that I've installed so it's not the solution.
Please help.
_**Updated the crash report!**_

**Comment by shedaniel** [comment]
install https://www.curseforge.com/minecraft/mc-mods/cloth-config/files
