### ISSUE TITLE
Chat Opening Crash

### ISSUE THREAD

**Issue by UltraBlackLinux** [shedaniel/slight-gui-modifications#31]
Hey there,
I am suddenly crashing when opening the chat with slight gui modifications: https://paste.ee/p/nK5i5 (NoSuchFieldError: offset)
This may be some mod incompatibility, but I don't know that at the moment.
Please look into it, 
Thanks!

EDIT: Stendhal is causing it -- Bruh wtf, Stendhal is not open source, ok, I guess I will uninstall that mod then, sucks to not be open source

**Comment by shedaniel** [comment]
Seems to be unrelated to SGM.
