### ISSUE TITLE
Could not find-Errors for MC 1.17.1

### ISSUE THREAD

**Issue by CommanderRedYT** [shedaniel/slight-gui-modifications#40]
For 1.16.4, I just had to put the jar into the mods folder.
In 1.17.1, this is the list I had to install:

- cloth-api-2.0.54.jar
- cloth-config-5.0.37-fabric.jar

I know, only two mods, but still, they weren't listed on the CurseForge page.

**Comment by shedaniel** [comment]
![image](https://user-images.githubusercontent.com/34910653/128367150-cde2ee47-3198-453c-9e54-c728c4dc7c01.png)
It's listed, please consider using the CurseForge app if you are new to this.
