### ISSUE TITLE
[Suggestion] A Feature related to GUI in your 'Slight' GUI Modifications mod.

### ISSUE THREAD

**Issue by singhantariksh** [shedaniel/slight-gui-modifications#54]
Heya,
I really wish your mod have a feature somewhat like this mod have : https://www.curseforge.com/minecraft/mc-mods/better-gui-scaling

What this does is, allows the user to change GUI is many different scale instead of just 3...

**Comment by shedaniel** [comment]
We do allow it, it is in the configs? It is in the vanilla scale format, but you can set decimal points

**Comment by singhantariksh** [comment]
I tried it in Optifine Config. It didn't worked, so I thought this won't work here too :p Thank you so much. I'll try doing that rn
