### ISSUE TITLE
Crash (I can't find any reason why)

### ISSUE THREAD

**Issue by ultra-black** [shedaniel/slight-gui-modifications#59]
I have done everything, I have 2.0.3, architectury-3.6.17, cloth-api-3.1.61.
Then I open it then I get this stupid crash 
[This stupid crash log file](https://github.com/shedaniel/slight-gui-modifications/files/8072797/crash.txt)

Please help me.

**Comment by ultra-black** [comment]
The log has been the same for the past 3 hours of debbugging

**Comment by shedaniel** [comment]
I think you might just have a broken install, please only open an issue if you think SGM is the cause of the crash.

**Comment by ultra-black** [comment]
I think SGM is the cause of the crash. After I removed it, it works.
