### ISSUE TITLE
1.18.2 Compatibility [ARRP]

### ISSUE THREAD

**Issue by Lolothepro** [shedaniel/slight-gui-modifications#64]
[crash-2022-03-06_12.53.01-client.txt](https://github.com/shedaniel/slight-gui-modifications/files/8192482/crash-2022-03-06_12.53.01-client.txt)

Part of the problem is that the ARRP is not up to date.

**Comment by shedaniel** [comment]
I don't think I bundle ARRP as with the latest version, you should download that
