### ISSUE TITLE
Incompatibility with two other mods

### ISSUE THREAD

**Issue by muluffel** [shedaniel/slight-gui-modifications#79]
(1.19)
Slight GUI Modifications seems to have incompatibilities when it is intalled together with [Optifabric ](https://www.curseforge.com/minecraft/mc-mods/optifabric/) (and [Optifine](https://optifine.net/home)) and [Borderless Mining](https://www.curseforge.com/minecraft/mc-mods/borderless-mining). Only the combination of those 3 mods crashes the game. No other combinations. See the following:

Optifabric (and Optifine ) + Borderless Mining = working
Optifabric (and Optifine ) + Slight GUI Modifications = working
Borderless Mining + Slight GUI Modifications = working
Borderless Mining + Optifabric (and Optifine ) + Slight GUI Modifications = [crash](https://mclo.gs/lpG4GpK)

```The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute 
entrypoint stage 'client' due to errors, provided by 'slight-
gui-modifications'!
Exit-Code: -1```

**Comment by shedaniel** [comment]
I do not care about Optifine

**Comment by muluffel** [comment]
wow ._.
so user friendly
