### ISSUE TITLE
Opening animations not moving text with gui

### ISSUE THREAD

**Issue by rayzchen** [shedaniel/slight-gui-modifications#86]
With this configuration:
![image](https://user-images.githubusercontent.com/54078384/185738268-e77f5b57-79e3-43f9-9f90-9cb1ea3293cf.png)
When I navigate through the menus the buttons fade in and slide in but the text doesn't move, so if I turn off the fade it looks very weird. Turning fade duration to 5000 makes it even more noticeable.
Texture pack: 1.18 Faithful 32x
Minecraft version: 1.19.2
Mod version: 2.3.0

**Comment by FireFragment** [comment]
Also happens for me

**Comment by FireFragment** [comment]
Maybe duplicate of #75?

**Comment by rayzchen** [comment]
It seems to be.
