### ISSUE TITLE
Crash when using ModMenu 7.1.0

### ISSUE THREAD

**Issue by HhiPyrene** [shedaniel/slight-gui-modifications#96]
[crash-2023-06-18_10.25.53-client.txt](https://github.com/shedaniel/slight-gui-modifications/files/11780569/crash-2023-06-18_10.25.53-client.txt)

**Comment by HhiPyrene** [comment]
ModMenu# 608

**Comment by HhiPyrene** [comment]
TerraformersMC/ModMenu#608

**Comment by shedaniel** [comment]
Fixed in 2.6.1
